### PR TITLE
Detect bad targets

### LINKED ISSUE #47: Validate all requested targets up front
Currently, each requested target is executed, and an exception is thrown only when the first unknown requested target is iterated through.

~Breaking, since this will prevent known requested targets from running before the unknown requested target is iterated through.~

### LINKED ISSUE #48: Validate dependencies up front
Currently, each requested target and dependency is executed, and an exception is thrown only when the first unknown dependency is iterated through.

~Breaking, since this will prevent known requested targets and dependencies from running before the unknown requested dependency is iterated through.~

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #47.
Fixes #48.

### CODE REVIEW

**Review by adamralph — CHANGES_REQUESTED** [review]
- In the case where more than one target does not exist, it would be nicer to report all of them in the exception message to avoid cycles of run, error, fix, run, error, fix, ...
- It looks like the check for missing dependencies only checks one level deep, is that correct? There could be a situation where I request the running of target x, which depends on target y, which depends on a non-existent target z.
- In the previous case, the exception message "Target z does not exist" would be cryptic to the user, who requested target x, and may not know about target z. I think it's probably necessary to express the dependency chain in the exception message.

**Comment by blairconrad** [comment]
1. No problem
2. I don't think so. All targets will be in the dictionary, and therefore all dependencies should be covered by the `SelectMany`. In the test, we run `default`, which depends on `pack`, which depends on `notarealdependency`
3. No problem

Thanks for the feedback.
I'm going to be on other task for next couple of days. I'll try to get an update to you near Wednesday.

**Comment by adamralph** [comment]
> 2. I don't think so. All targets will be in the dictionary, and therefore all dependencies should be covered by the SelectMany. In the test, we run default, which depends on pack, which depends on notarealdependency

Ahh.. now I see. You're validating the dependencies of _all_ the targets, not just those in the dependency of chain of the requested target(s). I guess that's also OK, since there's no point having a target defined with a dependency which doesn't exist, even if that target isn't going to be invoked.

**Comment by blairconrad** [comment]
Oh, if we report the path to the missing dependencies, it may not make
sense to report all missing dependencies, just the ones reachable from the
targets. Otherwise the output could get quite long...

**Comment by adamralph** [comment]
In that case, perhaps the algorithm should change to only care about dependencies which are part of the current call chain.

**Comment by blairconrad** [comment]
Closing this request, as the new approach will be significantly different. And I may end up submitting two PRs, one for each issue.

**Pull request closed without merging**
